[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.120.2",
    "psycopg2-binary>=2.9.11",
    "sqlalchemy>=2.0.44",
]
